// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN_tU6Q_54QchTbYORSw_gTnSncrnpQ30',
    appId: '1:247526764850:web:11f1a342bd8f6f14cfa72b',
    messagingSenderId: '247526764850',
    projectId: 'fishtech-c2f1f',
    authDomain: 'fishtech-c2f1f.firebaseapp.com',
    storageBucket: 'fishtech-c2f1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA54cFnygz2UaBXQp-z701p7KXmXjSe1BU',
    appId: '1:247526764850:android:7bf20852b2aaa5cacfa72b',
    messagingSenderId: '247526764850',
    projectId: 'fishtech-c2f1f',
    storageBucket: 'fishtech-c2f1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnS4jeVH2bSv5t28EHDBUL7MRQZcKkzQk',
    appId: '1:247526764850:ios:ac813e64f8c66bb6cfa72b',
    messagingSenderId: '247526764850',
    projectId: 'fishtech-c2f1f',
    storageBucket: 'fishtech-c2f1f.firebasestorage.app',
    iosBundleId: 'com.fishtech.fishtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnS4jeVH2bSv5t28EHDBUL7MRQZcKkzQk',
    appId: '1:247526764850:ios:ac813e64f8c66bb6cfa72b',
    messagingSenderId: '247526764850',
    projectId: 'fishtech-c2f1f',
    storageBucket: 'fishtech-c2f1f.firebasestorage.app',
    iosBundleId: 'com.fishtech.fishtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN_tU6Q_54QchTbYORSw_gTnSncrnpQ30',
    appId: '1:247526764850:web:8e8706cb6f10bdd8cfa72b',
    messagingSenderId: '247526764850',
    projectId: 'fishtech-c2f1f',
    authDomain: 'fishtech-c2f1f.firebaseapp.com',
    storageBucket: 'fishtech-c2f1f.firebasestorage.app',
  );

}